# @package models

_target_: src.layers.wavenet_vocoder.WaveNet

out_channels: 1
layers: 14
stacks: 2
residual_channels: 512
gate_channels: 512
skip_out_channels: 512
kernel_size: 3
dropout: 0.05
cin_channels: -1
gin_channels: -1
n_speakers: null 
upsample_conditional_features: false
upsample_net: ConvInUpsampleNetwork
upsample_params:
       upsample_scales: [4, 4, 4, 4]
scalar_input: false
use_speaker_embedding: false
output_distribution: Logistic
cin_pad: 0
